apiVersion: v1
kind: ServiceAccount
metadata:
  name: visa-processor
  namespace: payments-v2
  labels:
    app: visa-processor-v2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visa-processor-v2
  labels:
    app: visa-processor-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: visa-processor
    namespace: payments-v2

---
# Deployment named "visa-processor"
# Listens on :8080
# Vulnerable to struts
# Has SSH keys mounted
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visa-processor
  namespace: payments-v2
  labels:
    app: visa-processor-v2
    app.kubernetes.io/part-of: payments
  annotations:
    "admission.stackrox.io/break-glass": "jira-3423"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visa-processor-v2
  template:
    metadata:
      labels:
        app: visa-processor-v2
    spec:
      serviceAccountName: visa-processor
      volumes:
        - name: ssh-keys
          secret:
            secretName: ssh-keys
      containers:
        - image: quay.io/vuln/visa-processor:latest
          imagePullPolicy: Always
          name: visa-processor
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: ssh-keys
              mountPath: "/root/.ssh"
              readOnly: false
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
            privileged: true
          env:
            - name: DB_SERVICE_ADDR
              value: "external-db"
            - name: I_HAVE_A_SECRET
              value: "true"

---
# Service named "visa-processor-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visa-processor-v2
  name: visa-processor-service
  namespace: payments-v2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: visa-processor-v2
  type: ClusterIP
