apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
- namespace.yaml
- secrets.yaml
- rbac.yaml
- gateway
- mastercard-processor
- visa-processor
#- visa-processor-v2
