apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payments-secrets
  namespace: payments-v2
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-secrets
  namespace: payments-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: payments-secrets
subjects:
  - kind: User
    name: "joe@example.com"
    apiGroup: rbac.authorization.k8s.io