apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-app-demo
  namespace: openshift-gitops
spec:
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'http://gogs.gogs.svc.cluster.local:3000/developer/rhacs-app-demo.git'
    targetRevision: main
  project: default
