apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-app-demo
  namespace: openshift-gitops
spec:
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/ralvares/security-demos'
    targetRevision: main
  project: default
