apiVersion: v1
kind: Namespace
metadata:
  name: dev-team
  labels:
    custom.security/enforce: "true"
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
