apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipeline-demo
resources:
- namespace.yaml
- stackrox-image-check.yaml
- stackrox-image-scan.yaml
- stackrox-deployment-check.yaml
- rhacs-demo-pipeline.yaml