apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cosign
  namespace: pipeline-demo
spec:
  description: These tasks make it possible to use cosign within your Tekton pipelines cosign is a tool for signing and verifying software artifacts.
  params:
    - name: cosignkey
      type: string
    - name: image
      type: string
    - name: namespace
      type: string
  results:
    - description: The email from the certificate common name in JSON format
      name: email
      type: string
  steps:
    - computeResources: {}
      env:
        - name: COSIGN_EXPERIMENTAL
          value: '1'
      image: 'alpine'
      name: cosign
      script: |
        #!/bin/sh
        wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O /tmp/cosign
        chmod +x /tmp/cosign
        CMD="/tmp/cosign sign -y --recursive --key k8s://$(params.namespace)/$(params.cosignkey) $(params.image)"
        echo "${CMD}"
        ERR_MSG="Failed to sign $(params.image)"
        ${CMD} &> result
        err=$?
        cat result
        if [[ ${err} -ne 0 ]]; then
          echo "${ERR_MSG}"
          exit 1
        fi
      workingDir: /workspace/source
  workspaces:
    - name: source
