kind: Secret
apiVersion: v1
metadata:
  name: git-repo-auth
  namespace: pipeline-demo 
  annotations:
    tekton.dev/git-0: 'http://gogs.gogs.svc.cluster.local:3000'
data:
  password: ZGV2ZWxvcGVy
  username: ZGV2ZWxvcGVy
type: kubernetes.io/basic-auth
