---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: malware-image-scan
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Malware Scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Simple Demo - malware scanner
  params:
    - name: image
      type: string
      description: |
        Full name of image to check.
        Examples: 'quay.io/petr_ruzicka/malware-cryptominer-container:latest', '$(params.IMAGE)', '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      default: '$(params.IMAGE)'
  steps:
    - name: malware-scanning
      image: quay.io/ralvares/malware-detection@sha256:62515ea02241720c4724966211ce6facb52034c05c6d1860e8efe83f8a7dd555
      script: |
        #!/usr/bin/env sh
        /entrypoint.sh
      env:
        - name: IMAGE_NAME
          value: $(params.image)
        - name: HOME
          value: /tmp
