apiVersion: v1
kind: ServiceAccount
metadata:
  name: netpol
  namespace: pipeline-demo
secrets:
- name: git-repo-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:pipelines-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - pipelines-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:pipelines-scc
  namespace: northpole-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:pipelines-scc
subjects:
- kind: ServiceAccount
  name: netpol
  namespace: pipeline-demo 
