FROM maven as builder 

COPY . /usr/src/poc
WORKDIR /usr/src/poc
RUN sed -i 's/2.14.1/2.17.1/' pom.xml && mvn clean && mvn package

FROM registry.access.redhat.com/ubi8/ubi-minimal

COPY src/entrypoint /bin/

USER 1001

COPY --from=builder /usr/src/poc/target/log4j-rce-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/app-root/src/

ENTRYPOINT /bin/entrypoint
