apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gogs
resources:
- gogs.yaml
- namespace.yaml
- gogs-config.yaml
- ingress.yaml
- gogs-repomirror.yaml
- gogs-job.yaml
secretGenerator:
- literals:
  - password=admin123
  name: admin-secret
