apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  monitoring:
    openshift:
      enabled: true
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    resources:
      requests:
        cpu: 1m
        memory: 5Mi
        ephemeral-storage: 50Mi
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    replicas: 1
    timeoutSeconds: 20
    listenOnEvents: true
  sensor:
    resources:
      requests:
        cpu: 1m
        memory: 5Mi
        ephemeral-storage: 50Mi
  scannerV4:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer:
      scaling:
        autoScaling: Disabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 1
    scannerComponent: Default
  scanner:
    analyzer:
      resources:
        requests:
          cpu: 1m
          memory: 5Mi
          ephemeral-storage: 50Mi
      scaling:
        autoScaling: Disabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 1
    db:
      resources:
        requests:
          cpu: 1m
          memory: 5Mi
          ephemeral-storage: 50Mi
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: CORE_BPF
      forceCollection: false
      imageFlavor: Regular
      resources:
        requests:
          cpu: 1m
          memory: 5Mi
          ephemeral-storage: 50Mi
    compliance:
      resources:
        requests:
          cpu: 1m
          memory: 5Mi
          ephemeral-storage: 5Mi
    nodeInventory:
      resources:
        requests:
          cpu: 10m
          memory: 5Mi
          ephemeral-storage: 50Mi
    taintToleration: TolerateTaints
  clusterName: production
