apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: 30-day-scan-age
spec:
  categories:
  - Security Best Practices
  - Supply Chain Security
  criteriaLocked: true
  description: Alert on deployments with images that haven't been scanned in 30 days
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - 30-Day Scan Age
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Image Scan Age
      booleanOperator: OR
      negate: false
      values:
      - value: '30'
  rationale: Out-of-date scans may not identify the most recent CVEs.
  remediation: Integrate a scanner with the StackRox Kubernetes Security Platform
    to trigger scans automatically.
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
