apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: 90-day-image-age
spec:
  categories:
  - DevOps Best Practices
  - Security Best Practices
  - Supply Chain Security
  criteriaLocked: true
  description: Alert on deployments with images that haven't been updated in 90 days
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: Don't alert on kube-system namespace
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: kube-system
        label: null
    image: null
    expiration: null
  - name: Don't alert on istio-system namespace
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: istio-system
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - 90-Day Image Age
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Image Age
      booleanOperator: OR
      negate: false
      values:
      - value: '90'
  rationale: Base images are updated frequently with bug fixes and vulnerability patches.
    Image age exceeding 90 days may indicate a higher risk of vulnerabilities existing
    in the image.
  remediation: Rebuild your image, push a new minor version (with a new immutable
    tag), and update your service to use it.
  scope: []
  severity: LOW_SEVERITY
  disabled: false
