apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: add-command-used-instead-of-copy
spec:
  categories:
  - DevOps Best Practices
  - Docker CIS
  criteriaLocked: true
  description: Alert on deployments using an ADD command
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - ADD Command used instead of COPY
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Dockerfile Line
      booleanOperator: OR
      negate: false
      values:
      - value: ADD=.*
  rationale: ADD incorporates a broader set of capabilities than COPY, including the
    ability to specify URLs as the source argument and automatic unpacking of compressed
    files onto the local filesystem. The effects of ADD can be unpredictable and can
    lead to larger images. Unless ADD's additional capabilities are required, COPY
    is recommended.
  remediation: Replace ADD with COPY when adding new files to the image. Per https://docs.docker.com/develop/develop-images/dockerfile_best-practices,
    it is better to use RUN curl instead of ADD if you need to access a URL.
  scope: []
  severity: LOW_SEVERITY
  disabled: true
