apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: apache-struts-cve-2017-5638
spec:
  categories:
  - Vulnerability Management
  criteriaLocked: true
  description: Alert on deployments with images containing Apache Struts vulnerability
    CVE-2017-5638
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: 'GitOps - Apache Struts: CVE-2017-5638'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: CVE
      booleanOperator: OR
      negate: false
      values:
      - value: CVE-2017-5638
  rationale: CVE-2017-5638 is a serious and easily-exploitable vulnerability in Apache
    Struts.
  remediation: Rebuild your container with an updated version of Apache Struts.
  scope: []
  severity: CRITICAL_SEVERITY
  disabled: false
