apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: cap-sys-admin-capability-added
spec:
  categories:
  - Privileges
  criteriaLocked: true
  description: Alert on deployments with containers escalating with CAP_SYS_ADMIN
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - CAP_SYS_ADMIN capability added
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Add Capabilities
      booleanOperator: OR
      negate: false
      values:
      - value: SYS_ADMIN
  rationale: CAP_SYS_ADMIN grants an elevated level of privilege to a container that
    may not be necessary. https://lwn.net/Articles/486306/ explains what CAP_SYS_ADMIN
    does and points to possible alternatives.
  remediation: Ensure that the container really needs the CAP_SYS_ADMIN capability
    or use a userspace derivative.
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
