apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: crontab-execution
spec:
  categories:
  - System Modification
  criteriaLocked: true
  description: Detects the usage of the crontab scheduled jobs editor
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0003
    techniques:
    - T1053.003
  mitreVectorsLocked: true
  policyName: GitOps - crontab Execution
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: anacron|cron|crond|crontab
  rationale: Crontab running in a container with access to a shell makes it easier
    to 'clandestinely' schedule processes to run in order to better evade detection
  remediation: In Kubernetes, consider replacing your crontab with an orchestrator-native
    CronJob as part of Kube workload
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
