apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: docker-cis-5.16-ensure-that-the-host-s-ipc-namespace-is-not-shared
spec:
  categories:
  - Docker CIS
  criteriaLocked: true
  description: IPC (POSIX/SysV IPC) namespace provides separation of named shared
    memory segments, semaphores and message queues. The IPC namespace on the host
    should therefore not be shared with containers and should remain isolated.
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: Don't alert on deployment tuned in openshift-cluster-node-tuning-operator
      namespace
    deployment:
      name: tuned
      scope:
        cluster: ''
        namespace: openshift-cluster-node-tuning-operator
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: 'GitOps - Docker CIS 5.16: Ensure that the host''s IPC namespace is
    not shared'
  policySections:
  - sectionName: Section 1
    policyGroups:
    - fieldName: Host IPC
      booleanOperator: OR
      negate: false
      values:
      - value: 'true'
  rationale: The IPC namespace provides separation of IPC between the host and containers.
    If the host's IPC namespace is shared with the container, it would allow processes
    within the container to see all of IPC communications on the host system. This
    would remove the benefit of IPC level isolation between host and containers. An
    attacker with access to a container could get access to the host at this level
    with major consequences. The IPC namespace should therefore not be shared between
    the host and its containers.
  remediation: 'You should not create a deployment with `hostIPC: true`'
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
