apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: docker-cis-5.15-ensure-that-the-host-s-process-namespace-is-not-shared
spec:
  categories:
  - Docker CIS
  criteriaLocked: true
  description: The Process ID (PID) namespace isolates the process ID space, meaning
    that processes in different PID namespaces can have the same PID. This creates
    process level isolation between the containers and the host.
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: Don't alert on deployment apiserver-watcher-* in kube-system namespace
    deployment:
      name: apiserver-watcher-.*
      scope:
        cluster: ''
        namespace: kube-system
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment in openshift-kube-apiserver namespace
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-kube-apiserver
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment tuned in openshift-cluster-node-tuning-operator
      namespace
    deployment:
      name: tuned
      scope:
        cluster: ''
        namespace: openshift-cluster-node-tuning-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment ovnkube-node in openshift-ovn-kubernetes namespace
    deployment:
      name: ovnkube-node
      scope:
        cluster: ''
        namespace: openshift-ovn-kubernetes
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment machine-config-daemon in openshift-machine-config-operator
      namespace
    deployment:
      name: machine-config-daemon
      scope:
        cluster: ''
        namespace: openshift-machine-config-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on the openshift-sdn namespace
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-sdn
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment node-exporter in namespace openshift-monitoring
    deployment:
      name: node-exporter
      scope:
        cluster: ''
        namespace: openshift-monitoring
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment multus in namespace openshift-multus
    deployment:
      name: multus
      scope:
        cluster: ''
        namespace: openshift-multus
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: 'GitOps - Docker CIS 5.15: Ensure that the host''s process namespace
    is not shared'
  policySections:
  - sectionName: Section 1
    policyGroups:
    - fieldName: Host PID
      booleanOperator: OR
      negate: false
      values:
      - value: 'true'
  rationale: PID namespace provides separation between processes. It prevents system
    processes from being visible, and allows process ids to be reused including PID
    1. If the host's PID namespace is shared with containers, it would basically allow
    these to see all of the processes on the host system. This reduces the benefit
    of process level isolation between the host and the containers. Under these circumstances
    a malicious user who has access to a container could get access to processes on
    the host itself, manipulate them, and even be able to kill them. This could allow
    for the host itself being shut down, which could be extremely serious, particularly
    in a multi-tenanted environment. You should not share the host's process namespace
    with the containers running on it.
  remediation: 'You should not create a deployment with `hostPID: true`'
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
