apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: emergency-deployment-annotation
spec:
  categories:
  - Security Best Practices
  criteriaLocked: true
  description: 'Alert on deployments that use the emergency annotation (e.g. "admission.stackrox.io/break-glass":
    "ticket-1234") to circumvent StackRox Admission Controller checks'
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors:
  - tactic: TA0005
    techniques:
    - T1610
  mitreVectorsLocked: true
  policyName: GitOps - Emergency Deployment Annotation
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Disallowed Annotation
      booleanOperator: OR
      negate: false
      values:
      - value: admission.stackrox.io/break-glass=
  rationale: 'Ideally, all deployments should be validated before they are launched
    into the cluster; however, in case of emergency, annotations in the form of {
    "admission.stackrox.io/break-glass": "ticket-1234"} can be used to avoid those
    checks.'
  remediation: Redeploy your service and unset the emergency annotation.
  scope: []
  severity: HIGH_SEVERITY
  disabled: false
