apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: environment-variable-contains-secret
spec:
  categories:
  - Security Best Practices
  criteriaLocked: true
  description: Alert on deployments with environment variables that contain 'SECRET'
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: Don't alert on deployment noobaa-core in namespace openshift-storage
    deployment:
      name: noobaa-core
      scope:
        cluster: ''
        namespace: openshift-storage
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment noobaa-endpoint in namespace openshift-storage
    deployment:
      name: noobaa-endpoint
      scope:
        cluster: ''
        namespace: openshift-storage
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment ocs-operator in namespace openshift-storage
    deployment:
      name: ocs-operator
      scope:
        cluster: ''
        namespace: openshift-storage
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment ocm-agent in openshift-ocm-agent-operator namespace
    deployment:
      name: ocm-agent
      scope:
        cluster: ''
        namespace: openshift-ocm-agent-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on router-default in openshift-ingress namespace
    deployment:
      name: router-default
      scope:
        cluster: ''
        namespace: openshift-ingress
        label: null
    image: null
    expiration: null
  - name: Don't alert on image-registry in openshift-image-registry namespace
    deployment:
      name: image-registry
      scope:
        cluster: ''
        namespace: openshift-image-registry
        label: null
    image: null
    expiration: null
  - name: Don't alert on thanos-ruler-user-workload in openshift-user-workload-monitoring
      namespace
    deployment:
      name: thanos-ruler-user-workload
      scope:
        cluster: ''
        namespace: openshift-user-workload-monitoring
        label: null
    image: null
    expiration: null
  - name: Don't alert on klusterlet-addon-controller-v2 in namespace open-cluster-management
    deployment:
      name: klusterlet-addon-controller-v2
      scope:
        cluster: ''
        namespace: open-cluster-management
        label: null
    image: null
    expiration: null
  - name: Don't alert on managedcluster-import-controller-v2 in namespace multicluster-engine
    deployment:
      name: managedcluster-import-controller-v2
      scope:
        cluster: ''
        namespace: multicluster-engine
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Environment Variable Contains Secret
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Environment Variable
      booleanOperator: OR
      negate: false
      values:
      - value: RAW=.*SECRET.*|.*PASSWORD.*=
  rationale: Using secrets in environment variables may allow inspection into your
    secrets from the host or even through the orchestrator UI.
  remediation: Migrate your secrets from environment variables to orchestrator secrets
    or your security team's secret management solution.
  scope: []
  severity: HIGH_SEVERITY
  disabled: false
