apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: fixable-cvss-7
spec:
  categories:
  - Vulnerability Management
  criteriaLocked: true
  description: Alert on deployments with fixable vulnerabilities with a CVSS of at
    least 7
  enforcementActions:
  - FAIL_BUILD_ENFORCEMENT
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Fixable CVSS >= 7
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Fixed By
      booleanOperator: OR
      negate: false
      values:
      - value: .*
    - fieldName: CVSS
      booleanOperator: OR
      negate: false
      values:
      - value: '>= 7.000000'
  rationale: Known vulnerabilities make it easier for adversaries to exploit your
    application. You can fix these high-severity vulnerabilities by updating to a
    newer version of the affected component(s).
  remediation: Use your package manager to update to a fixed version in future builds
    or speak with your security team to mitigate the vulnerabilities.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
