apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: images-with-no-scans
spec:
  categories:
  - Supply Chain Security
  - Vulnerability Management
  criteriaLocked: true
  description: Alert on deployments with images that have not been scanned
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Images with no scans
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Unscanned Image
      booleanOperator: OR
      negate: false
      values:
      - value: 'true'
  rationale: Without a scan, there will be no vulnerability information for this image
  remediation: Configure the appropriate registry and scanner integrations so that
    StackRox can obtain scans for your images.
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: true
