apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: improper-usage-of-orchestrator-secrets-volume
spec:
  categories:
  - DevOps Best Practices
  criteriaLocked: true
  description: Alert on deployments that use a Dockerfile with 'VOLUME /run/secrets'
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Improper Usage of Orchestrator Secrets Volume
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Dockerfile Line
      booleanOperator: OR
      negate: false
      values:
      - value: VOLUME=(?:(?:[,\[\s]?)|(?:.*[,\s]+))/run/secrets(?:$|[,\]\s]).*
  rationale: /run/secrets is a path for secrets that gets populated by the orchestrator.
    Volumes should not be used for secrets, and data mounts should have a separate
    mount path.
  remediation: Mount the volume to a different path. If secrets are stored in the
    volume, utilize the orchestrator secrets or your security team's secret management
    solution instead.
  scope: []
  severity: LOW_SEVERITY
  disabled: false
