apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: linux-group-add-execution
spec:
  categories:
  - Privileges
  - System Modification
  criteriaLocked: true
  description: Detects when the 'addgroup' or 'groupadd' binary is executed, which
    can be used to add a new linux group.
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0003
    techniques:
    - T1098
    - T1136
  mitreVectorsLocked: true
  policyName: GitOps - Linux Group Add Execution
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: addgroup|groupadd
  rationale: Groups added in run time can be used to take ownership of files and processes
  remediation: Consider using a base image that doesn't have a shell such as SCRATCH
    or gcr.io/distroless. If not, modify your Dockerfile to use the exec form of CMD/ENTRYPOINT
    (["using braces"]) instead of the shell form (no braces)
  scope: []
  severity: HIGH_SEVERITY
  disabled: false
