apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: login-binaries
spec:
  categories:
  - Security Best Practices
  criteriaLocked: true
  description: Processes that indicate login attempts
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0004
    techniques:
    - T1548
  mitreVectorsLocked: true
  policyName: GitOps - Login Binaries
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: login|systemd|systemd|systemd-logind|gosu|su|nologin|faillog|lastlog|newgrp|sg
  rationale: Login processes at runtime are unusual in a container
  remediation: Ensure that the base image used to create the Dockerfile doesn't have
    login binaries packaged with it.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
