apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: netcat-execution-detected
spec:
  categories:
  - Network Tools
  criteriaLocked: true
  description: Detects execution of netcat in a container
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0007
    techniques:
    - T1046
  mitreVectorsLocked: true
  policyName: GitOps - Netcat Execution Detected
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: nc
  rationale: netcat is a known malicious process
  remediation: Consider removing package managers during the build process that could
    be used to download such software. Check that exposed ports don't allow for remote
    code execution
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
