apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: nmap-execution
spec:
  categories:
  - Network Tools
  criteriaLocked: true
  description: Alerts when the nmap process launches in a container during run time
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0007
    techniques:
    - T1046
  mitreVectorsLocked: true
  policyName: GitOps - nmap Execution
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: nmap
  rationale: Nmap can be used to probe a running container's network to enumerate
    open ports and perform other actions such as OS version detection and launching
    over-the-network scripted attacks
  remediation: Consider removing package managers during the build process that could
    be used to download such software. Check that exposed ports don't allow for remote
    code execution
  scope: []
  severity: HIGH_SEVERITY
  disabled: false
