apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: openshift-kubeadmin-secret-accessed
spec:
  categories:
  - Anomalous Activity
  - Kubernetes Events
  criteriaLocked: true
  description: Alert when the kubeadmin secret is accessed
  enforcementActions: []
  eventSource: AUDIT_LOG_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0006
    techniques:
    - T1552.007
  - tactic: TA0007
    techniques:
    - T1613
  mitreVectorsLocked: true
  policyName: 'GitOps - OpenShift: Kubeadmin Secret Accessed'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Kubernetes Resource
      booleanOperator: OR
      negate: false
      values:
      - value: SECRETS
    - fieldName: Kubernetes API Verb
      booleanOperator: OR
      negate: false
      values:
      - value: GET
    - fieldName: Kubernetes Resource Name
      booleanOperator: OR
      negate: false
      values:
      - value: kubeadmin
    - fieldName: Kubernetes User Name
      booleanOperator: OR
      negate: true
      values:
      - value: system:serviceaccount:openshift-authentication-operator:authentication-operator
      - value: system:apiserver
      - value: system:serviceaccount:openshift-authentication:oauth-openshift
      - value: system:serviceaccount:openshift-compliance:api-resource-collector
      - value: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
  rationale: Kubeadmin is the default administrative user for OpenShift and can be
    used to obtain full administrative access to the cluster. Investigating if this
    was accessed for valid business purposes can help organizations to control the
    use of administrative privileges
  remediation: Audit the access carefully to ensure that this secret is only accessed
    for valid business purposes.
  scope: []
  severity: HIGH_SEVERITY
  disabled: false
