apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: openshift-kubernetes-secret-accessed-by-an-impersonated-user
spec:
  categories:
  - Anomalous Activity
  - Kubernetes Events
  criteriaLocked: true
  description: Alert when user impersonation is used to access a secret within the
    cluster.
  enforcementActions: []
  eventSource: AUDIT_LOG_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0004
    techniques:
    - T1134.001
  - tactic: TA0006
    techniques:
    - T1552.007
  mitreVectorsLocked: true
  policyName: 'GitOps - OpenShift: Kubernetes Secret Accessed by an Impersonated User'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Kubernetes Resource
      booleanOperator: OR
      negate: false
      values:
      - value: SECRETS
    - fieldName: Kubernetes API Verb
      booleanOperator: OR
      negate: false
      values:
      - value: GET
    - fieldName: Is Impersonated User
      booleanOperator: OR
      negate: false
      values:
      - value: 'true'
    - fieldName: Kubernetes User Name
      booleanOperator: OR
      negate: true
      values:
      - value: system:serviceaccount:openshift-insights:operator
  rationale: Users with impersonation access allows users to invoke any command as
    a different user, typically for troubleshooting purposes (i.e using the oc --as
    command). This may be used to bypass existing security controls such as RBAC.
  remediation: Audit usage of impersonation when accessing secrets to ensure this
    access is used for valid business purposes.
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
