apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: openshift-central-admin-secret-accessed
spec:
  categories:
  - Anomalous Activity
  - Kubernetes Events
  criteriaLocked: true
  description: Alert when the Central secret is accessed.
  enforcementActions: []
  eventSource: AUDIT_LOG_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0006
    techniques:
    - T1552.007
  - tactic: TA0007
    techniques:
    - T1613
  mitreVectorsLocked: true
  policyName: 'GitOps - OpenShift: Central Admin Secret Accessed'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Kubernetes Resource
      booleanOperator: OR
      negate: false
      values:
      - value: SECRETS
    - fieldName: Kubernetes API Verb
      booleanOperator: OR
      negate: false
      values:
      - value: GET
      - value: PATCH
      - value: UPDATE
    - fieldName: Kubernetes Resource Name
      booleanOperator: OR
      negate: false
      values:
      - value: central-htpasswd
    - fieldName: Kubernetes User Name
      booleanOperator: OR
      negate: true
      values:
      - value: system:serviceaccount:openshift-authentication-operator:rhacs-operator-controller-manager
      - value: system:serviceaccount:rhacs-operator:rhacs-operator-controller-manager
  rationale: The Central secret can be used to login to the Central user interface
    as the admin user. This secret is generally salted and hashed by default in the
    data.htpasswd field, but may contain a base64 encoded password in the field data.password
    (if deployed with an Operator). This field may be safely removed. This secret
    should only be accessed for break glass troubleshooting and initial configuration.
    An update or access of this secret may indicate that it will be used to administer
    and configure security controls.
  remediation: Ensure that the Central admin secret was accessed for valid buiness
    purposes.
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
