apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: password-binaries
spec:
  categories:
  - System Modification
  criteriaLocked: true
  description: Processes that indicate attempts to change passwd
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions:
  - name: Don't alert on deployment machine-config-daemon in openshift-machine-config-operator
      namespace
    deployment:
      name: machine-config-daemon
      scope:
        cluster: ''
        namespace: openshift-machine-config-operator
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0003
    techniques:
    - T1098
  mitreVectorsLocked: true
  policyName: GitOps - Password Binaries
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: shadowconfig|grpck|pwunconv|grpconv|pwck|groupmod|vipw|pwconv|useradd|newusers|cppw|chpasswd|usermod|groupadd|groupdel|grpunconv|chgpasswd|userdel|chage|chsh|gpasswd|chfn|expiry|passwd|vigr|cpgr
  rationale: Attempts to change password during runtime in containers is unusual
  remediation: Ensure that the base image used to create the Dockerfile doesn't have
    passwd binaries packaged with it.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
