apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: pod-service-account-token-automatically-mounted
spec:
  categories:
  - Privileges
  - Security Best Practices
  criteriaLocked: true
  description: Protect pod default service account tokens from compromise by minimizing
    the mounting of the default service account token to only those pods whose application
    requires interaction with the Kubernetes API.
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions:
  - name: Don't alert on deployment kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-2.c.acs-team-temp-dev.internal
      in namespace openshift-config-machine-operator
    deployment:
      name: kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-2.c.acs-team-temp-dev.internal
      scope:
        cluster: ''
        namespace: openshift-config-machine-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-1.c.acs-team-temp-dev.internal
      in namespace openshift-config-machine-operator
    deployment:
      name: kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-1.c.acs-team-temp-dev.internal
      scope:
        cluster: ''
        namespace: openshift-config-machine-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-0.c.acs-team-temp-dev.internal
      in namespace openshift-config-machine-operator
    deployment:
      name: kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-master-0.c.acs-team-temp-dev.internal
      scope:
        cluster: ''
        namespace: openshift-config-machine-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-worker-c-cfh9c
      in namespace openshift-config-machine-operator
    deployment:
      name: kube-rbac-proxy-crio-bm-ocp-shift-left-vxhch-worker-c-cfh9c
      scope:
        cluster: ''
        namespace: openshift-config-machine-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment haproxy-* in namespace openshift-vsphere-infra
    deployment:
      name: haproxy-.*
      scope:
        cluster: ''
        namespace: openshift-vsphere-infra
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment keepalived in namespace openshift-vsphere-infra
    deployment:
      name: keepalived-.*
      scope:
        cluster: ''
        namespace: openshift-vsphere-infra
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment coredns-* in namespace openshift-vsphere-infra
    deployment:
      name: coredns-.*
      scope:
        cluster: ''
        namespace: openshift-vsphere-infra
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment apiserver-watcher-* in namespace openshift-kube-apiserver
    deployment:
      name: apiserver-watcher-.*
      scope:
        cluster: ''
        namespace: openshift-kube-apiserver
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-apiserver-* in namespace openshift-kube-apiserver
    deployment:
      name: kube-apiserver-.*
      scope:
        cluster: ''
        namespace: openshift-kube-apiserver
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-apiserver-guard-* in namespace openshift-kube-apiserver
    deployment:
      name: kube-apiserver-guard-.*
      scope:
        cluster: ''
        namespace: openshift-kube-apiserver
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment openshift-kube-scheduler-* in namespace openshift-kube-scheduler
    deployment:
      name: openshift-kube-scheduler-.*
      scope:
        cluster: ''
        namespace: openshift-kube-scheduler
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment openshift-kube-scheduler-guard-* in namespace
      openshift-kube-scheduler
    deployment:
      name: openshift-kube-scheduler-guard-.*
      scope:
        cluster: ''
        namespace: openshift-kube-scheduler
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment etcd-* in namespace openshift-etcd
    deployment:
      name: etcd-.*
      scope:
        cluster: ''
        namespace: openshift-etcd
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment etcd-guard-* in namespace openshift-etcd
    deployment:
      name: etcd-guard-.*
      scope:
        cluster: ''
        namespace: openshift-etcd
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-controller-manager-* in namespace openshift-kube-controller-manager
    deployment:
      name: kube-controller-manager-.*
      scope:
        cluster: ''
        namespace: openshift-kube-controller-manager
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment kube-controller-manager-guard* in namespace openshift-kube-controller-manager
    deployment:
      name: kube-controller-manager-guard.*
      scope:
        cluster: ''
        namespace: openshift-kube-controller-manager
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment splunkforwarder-ds in openshift-security namespace
    deployment:
      name: splunkforwarder-ds
      scope:
        cluster: ''
        namespace: openshift-security
        label: null
    image: null
    expiration: null
  - name: Don't alert on namespace openshift-kube-apiserver
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-kube-apiserver
        label: null
    image: null
    expiration: null
  - name: Don't alert on namespace openshift-kube-scheduler
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-kube-scheduler
        label: null
    image: null
    expiration: null
  - name: Don't alert on namespace openshift-etcd
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-etcd
        label: null
    image: null
    expiration: null
  - name: Don't alert on namespace openshift-kube-controller-manager
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: openshift-kube-controller-manager
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment blackbox-exporter in  openshift-route-monitor-operator
      namespace
    deployment:
      name: blackbox-exporter
      scope:
        cluster: ''
        namespace: openshift-route-monitor-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment token-refresher in openshift-monitoring namespace
    deployment:
      name: token-refresher
      scope:
        cluster: ''
        namespace: openshift-monitoring
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment downloads in openshift-console namespace
    deployment:
      name: downloads
      scope:
        cluster: ''
        namespace: openshift-console
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment csi-snapshot-webhook in openshift-cluster-storage-operator
      namepsace
    deployment:
      name: csi-snapshot-webhook
      scope:
        cluster: ''
        namespace: openshift-cluster-storage-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment network-operator in openshift-network-operator
      namespace
    deployment:
      name: network-operator
      scope:
        cluster: ''
        namespace: openshift-network-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment network-check-target in openshift-network-diagnostics
      Namespace
    deployment:
      name: network-check-target
      scope:
        cluster: ''
        namespace: openshift-network-diagnostics
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment machine-config-operator in openshift-machine-config-operator
      Namespace
    deployment:
      name: machine-config-operator
      scope:
        cluster: ''
        namespace: openshift-machine-config-operator
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment ingress-canary in openshift-ingress-canary Namespace
    deployment:
      name: ingress-canary
      scope:
        cluster: ''
        namespace: openshift-ingress-canary
        label: null
    image: null
    expiration: null
  - name: 'Don''t alert on deployment cluster-proxy-service-proxy in namespace open-cluster-management-agent-addon '
    deployment:
      name: cluster-proxy-service-proxy
      scope:
        cluster: ''
        namespace: open-cluster-management-agent-addon
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment multus in namespace openshift-multus
    deployment:
      name: multus
      scope:
        cluster: ''
        namespace: openshift-multus
        label: null
    image: null
    expiration: null
  - name: Don't alert on deployment validation-webhook in namespace openshift-validation-webhook
    deployment:
      name: validation-webhook
      scope:
        cluster: ''
        namespace: openshift-validation-webhook
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Pod Service Account Token Automatically Mounted
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Automount Service Account Token
      booleanOperator: OR
      negate: false
      values:
      - value: 'true'
    - fieldName: Service Account
      booleanOperator: OR
      negate: false
      values:
      - value: default
    - fieldName: Namespace
      booleanOperator: OR
      negate: true
      values:
      - value: kube-system
  rationale: By default, Kubernetes automatically provisions a service account for
    each pod and mounts the secret at runtime. This service account is not typically
    used. If this pod is compromised and the compromised user has access to the service
    account, the service account could be used to escalate privileges within the cluster.
    To reduce the likelihood of privilege escalation this service account should not
    be mounted by default unless the pod requires direct access to the Kubernetes
    API as part of the pods functionality.
  remediation: 'Add `automountServiceAccountToken: false` or a value distinct from
    ''default'' for the `serviceAccountName` key to the deployment''s Pod configuration.'
  scope: []
  severity: MEDIUM_SEVERITY
  disabled: false
