apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: rapid-reset-denial-of-service-vulnerability-in-http-2-protocol
spec:
  categories:
  - Vulnerability Management
  criteriaLocked: true
  description: Alert on deployments with images containing components that are susceptible
    to a Denial of Service (DoS) vulnerability for HTTP/2 servers.
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: 'GitOps - Rapid Reset: Denial of Service Vulnerability in HTTP/2 Protocol'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: CVE
      booleanOperator: OR
      negate: false
      values:
      - value: CVE-2023-44487
      - value: CVE-2023-39325
    - fieldName: Severity
      booleanOperator: OR
      negate: false
      values:
      - value: '>=IMPORTANT'
  rationale: This is a flaw in the handling of multiplexed streams in http/2. A client
    can rapidly create a request and immediately reset them, which creates extra work
    for the server while avoiding hitting any server-side limits, resulting in a denial
    of service attack.
  remediation: Upgrade vulnerable components or images to the latest version.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
