apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: secret-mounted-as-environment-variable
spec:
  categories:
  - Security Best Practices
  criteriaLocked: true
  description: Alert on deployments with Kubernetes secret mounted as environment
    variable
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Secret Mounted as Environment Variable
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Environment Variable
      booleanOperator: OR
      negate: false
      values:
      - value: SECRET_KEY==
  rationale: Using secrets in environment variables may allow inspection into your
    secrets from the host.
  remediation: Migrate your secrets from environment variables to your security team's
    secret management solution.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
