apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: setuid-processes
spec:
  categories:
  - System Modification
  criteriaLocked: true
  description: Processes that are known to use setuid binaries
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0004
    techniques:
    - T1548.001
  - tactic: TA0005
    techniques:
    - T1548.001
  mitreVectorsLocked: true
  policyName: GitOps - SetUID Processes
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: sshd|dbus-daemon-lau|ping|ping6|critical-stack-|pmmcli|filemng|PassengerAgent|bwrap|osdetect|nginxmng|sw-engine-fpm|start-stop-daem
  rationale: setuid permits users to run certain programs with escalated privileges
  remediation: Ensure that the base image used to create the Dockerfile doesn't have
    setuid software packaged with it.
  scope: []
  severity: HIGH_SEVERITY
  disabled: true
