apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: systemd-execution
spec:
  categories:
  - System Modification
  criteriaLocked: true
  description: Detected usage of the systemd service manager
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions: []
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0003
    techniques:
    - T1543.002
  - tactic: TA0004
    techniques:
    - T1543.002
  mitreVectorsLocked: true
  policyName: GitOps - systemd Execution
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: systemd
  rationale: The systemd service manager is generally not used in containers, and
    its use could indicate suspicious activity
  remediation: Remove systemd from the image before deploying, or consider using a
    base image that doesn't bundle systemd
  scope: []
  severity: LOW_SEVERITY
  disabled: false
