apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: systemctl-execution
spec:
  categories:
  - System Modification
  criteriaLocked: true
  description: Detected usage of the systemctl service manager
  enforcementActions: []
  eventSource: DEPLOYMENT_EVENT
  exclusions:
  - name: Don't alert on StackRox namespace
    deployment:
      name: ''
      scope:
        cluster: ''
        namespace: stackrox
        label: null
    image: null
    expiration: null
  isDefault: false
  lifecycleStages:
  - RUNTIME
  mitreAttackVectors:
  - tactic: TA0003
    techniques:
    - T1543.002
  - tactic: TA0004
    techniques:
    - T1543.002
  mitreVectorsLocked: true
  policyName: GitOps - systemctl Execution
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Process Name
      booleanOperator: OR
      negate: false
      values:
      - value: systemctl
    - fieldName: Process Arguments
      booleanOperator: OR
      negate: true
      values:
      - value: --version
  rationale: The systemctl service manager is generally not used in containers, and
    its use could indicate suspicious activity
  remediation: Remove systemctl from the image before deploying, or consider using
    a base image that doesn't bundle systemctl
  scope: []
  severity: LOW_SEVERITY
  disabled: false
