apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: wget-in-image
spec:
  categories:
  - Security Best Practices
  criteriaLocked: true
  description: Alert on deployments with wget present
  enforcementActions: []
  eventSource: NOT_APPLICABLE
  exclusions: []
  isDefault: false
  lifecycleStages:
  - BUILD
  - DEPLOY
  mitreAttackVectors: []
  mitreVectorsLocked: true
  policyName: GitOps - Wget in Image
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Image Component
      booleanOperator: OR
      negate: false
      values:
      - value: wget=
  rationale: Leaving download tools like wget in an image makes it easier for attackers
    to use compromised containers, since they can easily download software.
  remediation: Use your package manager's "remove" command to remove wget from the
    image build for production containers.
  scope: []
  severity: LOW_SEVERITY
  disabled: true
