---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  labels:
    # Recommended for monitoring the operator itself
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  # RHACS operator typically supports AllNamespaces, 
  # but we define the group here for local management.
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  # 'stable' is the recommended channel for production
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace